### ISSUE TITLE
Jobs.collection on Client

### ISSUE THREAD

**Issue by 67726e** [wildhart/meteor.jobs#12]
I am trying to put together a dashboard on my application that lists the failed jobs with the purpose of allowing me to trigger a re-run of the failed job.

Currently the package appears to be [configured](https://github.com/wildhart/meteor.jobs/blob/master/package.js#L12) as server only, meaning I cannot access the `Jobs` object or its `Jobs.collection` property on the client-side.

Would it be possible to at least provide the `Jobs.collection` on the client-side?

**Comment by wildhart** [comment]
This is entirely possible.  Normally you wouldn't expose the jobs collection to users, but on your admin dashboard you can create the jobs collection with:
```
// imports/ui/Admin/Dashboard.Vue   (I'm using Vue....)
<template>
...
</template>

<script>
const jobsCollection = new Mongo.Collection("jobs_data");

...

export default {
    ...
    meteor: {
        $subscribe: {
            jobs: [],
        },
        jobs() {
            return jobsCollection.find({},{sort:{due: -1}});
        },
    },
....
```

Then you need a publication on the server, using whatever filter and security you want.  The jobs collection is exposed on the server with [`Jobs.collecton`](https://github.com/wildhart/meteor.jobs#jobscollection)
```
// server/publications/jobs.js

import { Jobs } from 'meteor/wildhart:jobs';

Meteor.publish("jobs", function() {
    if (this.userId != __whatever_your_super_admin_id_is__) return [];

    return Jobs.collection.find({}, {fields: {
        name:1,
        due:1,
        state:1,
        arguments: {$slice: 1} // return only the first item in the array of arguments
    } as any});
});
```

Then you can implement whatever methods you need to operate on the Jobs collection:
```
// server/methods/jobs.js

Meteor.methods({
    retryFailedJob(jobId) {
        if (this.userId != __whatever_your_super_admin_id_is__) throw new Meteor.Error('not admin');

        // assuming the job is in the past, this will cause it to re-run immediately.
        const nUpdated = Jobs.collection.update({_id: jobId, state: 'failure'}, {$set: {state: 'pending'}});
        return nUpdated;
    },
});
```

**Comment by 67726e** [comment]
What you're suggesting regarding the client-side Mongo collection does not appear to be possible, hence the issue:

```
Error: There is already a collection named "jobs_data"
    at new Collection (packages/mongo/collection.js:122:15)
    at module (imports/data/withAllJobs.js:7:20)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/gnelson/.meteor/packages/modules/.0.16.0.16gel8o.edwa++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
    at module (imports/data/index.js:1:323)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/gnelson/.meteor/packages/modules/.0.16.0.16gel8o.edwa++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/accounts.js:1:223)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/gnelson/.meteor/packages/modules/.0.16.0.16gel8o.edwa++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/main.js:1:33)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by 67726e** [comment]
Disregard the last, this error was caused because of imports:

```
// data/index.js
export * from './collections';
export * from '...';
export * from '...';
```

I defined collections under `imports/data/collection.js` which is imported both into the server and client code. This caused the duplicate error!
