### ISSUE TITLE
do not support 'startupDelay' configure parameter

### ISSUE THREAD

**Issue by weilitao** [wildhart/meteor.jobs#13]
When I call
```
 Jobs.configure({
  startupDelay: 20 * 1000,
  log: false,
});
```
below error occurred.

It looks that you forgot check this parameter in jobs.ts

```
W20210822-22:29:26.154(8)? (STDERR) errorClass [Error]: Match error: Unknown key in field startupDelay
W20210822-22:29:26.155(8)? (STDERR)     at check (packages/check/match.js:36:17)
W20210822-22:29:26.155(8)? (STDERR)     at Object.configure (packages/wildhart:jobs/jobs.ts:71:3)
W20210822-22:29:26.155(8)? (STDERR)     at module (imports/startup/server/job.js:6:6)
W20210822-22:29:26.155(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210822-22:29:26.156(8)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210822-22:29:26.156(8)? (STDERR)     at Module.moduleLink [as link] (/Users/weilitao/Sync/local/.meteor/packages/modules/.0.16.0.1vgf3j2.535sj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210822-22:29:26.156(8)? (STDERR)     at module (imports/startup/server/index.js:1:148)
W20210822-22:29:26.157(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210822-22:29:26.157(8)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210822-22:29:26.157(8)? (STDERR)     at Module.moduleLink [as link] (/Users/weilitao/Sync/local/.meteor/packages/modules/.0.16.0.1vgf3j2.535sj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210822-22:29:26.157(8)? (STDERR)     at module (server/main.js:1:8)
W20210822-22:29:26.157(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210822-22:29:26.158(8)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210822-22:29:26.158(8)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20210822-22:29:26.158(8)? (STDERR)     at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/app/app.js:3082:15
W20210822-22:29:26.158(8)? (STDERR)     at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/boot.js:401:38
W20210822-22:29:26.158(8)? (STDERR)     at Array.forEach (<anonymous>)
W20210822-22:29:26.158(8)? (STDERR)     at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/boot.js:226:21
W20210822-22:29:26.158(8)? (STDERR)     at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/boot.js:464:7
W20210822-22:29:26.159(8)? (STDERR)     at Function.run (/Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/profile.js:280:14)
W20210822-22:29:26.159(8)? (STDERR)     at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/boot.js:463:13 {
W20210822-22:29:26.159(8)? (STDERR)   path: 'startupDelay',
W20210822-22:29:26.159(8)? (STDERR)   sanitizedError: errorClass [Error]: Match failed [400]
W20210822-22:29:26.159(8)? (STDERR)       at errorClass.<anonymous> (packages/check/match.js:91:27)
W20210822-22:29:26.159(8)? (STDERR)       at new errorClass (packages/meteor.js:655:17)
W20210822-22:29:26.160(8)? (STDERR)       at check (packages/check/match.js:36:17)
W20210822-22:29:26.160(8)? (STDERR)       at Object.configure (packages/wildhart:jobs/jobs.ts:71:3)
W20210822-22:29:26.160(8)? (STDERR)       at module (imports/startup/server/job.js:6:6)
W20210822-22:29:26.160(8)? (STDERR)       at fileEvaluate (packages/modules-runtime.js:336:7)
W20210822-22:29:26.160(8)? (STDERR)       at Module.require (packages/modules-runtime.js:238:14)
W20210822-22:29:26.160(8)? (STDERR)       at Module.moduleLink [as link] (/Users/weilitao/Sync/local/.meteor/packages/modules/.0.16.0.1vgf3j2.535sj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210822-22:29:26.160(8)? (STDERR)       at module (imports/startup/server/index.js:1:148)
W20210822-22:29:26.161(8)? (STDERR)       at fileEvaluate (packages/modules-runtime.js:336:7)
W20210822-22:29:26.161(8)? (STDERR)       at Module.require (packages/modules-runtime.js:238:14)
W20210822-22:29:26.161(8)? (STDERR)       at Module.moduleLink [as link] (/Users/weilitao/Sync/local/.meteor/packages/modules/.0.16.0.1vgf3j2.535sj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210822-22:29:26.161(8)? (STDERR)       at module (server/main.js:1:8)
W20210822-22:29:26.161(8)? (STDERR)       at fileEvaluate (packages/modules-runtime.js:336:7)
W20210822-22:29:26.161(8)? (STDERR)       at Module.require (packages/modules-runtime.js:238:14)
W20210822-22:29:26.162(8)? (STDERR)       at require (packages/modules-runtime.js:258:21)
W20210822-22:29:26.162(8)? (STDERR)       at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/app/app.js:3082:15
W20210822-22:29:26.162(8)? (STDERR)       at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/boot.js:401:38
W20210822-22:29:26.162(8)? (STDERR)       at Array.forEach (<anonymous>)
W20210822-22:29:26.162(8)? (STDERR)       at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/boot.js:226:21
W20210822-22:29:26.162(8)? (STDERR)       at /Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/boot.js:464:7
W20210822-22:29:26.162(8)? (STDERR)       at Function.run (/Users/weilitao/Sync/Code/CapForest/.meteor/local/build/programs/server/profile.js:280:14) {
W20210822-22:29:26.163(8)? (STDERR)     isClientSafe: true,
W20210822-22:29:26.163(8)? (STDERR)     error: 400,
W20210822-22:29:26.163(8)? (STDERR)     reason: 'Match failed',
W20210822-22:29:26.163(8)? (STDERR)     details: undefined,
W20210822-22:29:26.163(8)? (STDERR)     errorType: 'Meteor.Error'
W20210822-22:29:26.163(8)? (STDERR)   },
W20210822-22:29:26.163(8)? (STDERR)   errorType: 'Match.Error'
W20210822-22:29:26.163(8)? (STDERR) }
```

**Comment by wildhart** [comment]
Thanks for reporting this @weilitao.  This has been fixed in version 1.0.13.
